name: Cache node_modules
description: Cache node_modules after install
runs:
  using: composite
  steps:
    - name: Cache node_modules
      uses: actions/cache@v2
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: yarn-cache-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      shell: bash
      run: corepack enable && npm i install
